[PATHS]
TEMPLATE_PATH = E:\python_source\需求导入\更新导入模板（20260408）.xlsx
INPUT_PATHS =
    E:\python_source\需求导入\业务要求(20260415-记录数19).xlsx
    E:\python_source\需求导入\业务要求(20260415-记录数9).xlsx

; 对 "接收日期": ["创建时间", "回复时间/ITM回函时间"], 的映射规则做了拆分
; 按照李卫的映射关系补充了新的映射关系
Title_Map =
    {
      "要求编号": "工单编号/ITM编号",
      "领域组": "创建人机构",
      "接收日期": "创建时间",
      "要求标题": "工单概要",
      "要求正文": "工单详情描述",
      "最终意见": "处理意见",
      "客户/用户": "客户名称",
      "需求归口部门": "总行主管部门/总行提出部门",
      "分行实施意见": "分行实施意见",
      "最终审批日期": "回复时间/ITM回函时间",
      "业务需求实施复杂度": "实施复杂度",
      "结论": "实施结论"
    }

TaskAssigner_Map =
    {
      "北京市分行": "陈进进",
      "深圳市分行": "姚刚",
      "河南省分行": "姚刚",
      "辽宁省分行": "姚刚",
      "黑龙江省分行": "姚刚",
      "新疆维吾尔自治区分行": "李卫",
      "湖北省分行": "李卫",
      "甘肃省分行": "李卫",
      "福建省分行": "李卫",
      "厦门市分行": "李卫",
      "江西省分行": "刘贵军",
      "贵州省分行": "刘贵军",
      "上海市分行": "刘贵军",
      "安徽省分行": "刘贵军",
      "苏州分行": "刘贵军",
      "重庆市分行": "刘振科",
      "宁波市分行": "刘振科",
      "天津市分行": "刘振科",
      "内蒙古自治区分行": "刘振科",
      "广西壮族自治区分行": "杨立",
      "宁夏区分行": "杨立",
      "青海省分行": "杨立",
      "西藏自治区分行": "杨立",
      "陕西省分行": "杨立",
      "河北省分行": "高一冰",
      "大连市分行": "高一冰",
      "海南省分行": "高一冰",
      "湖南省分行": "高一冰",
      "吉林省分行": "张峰",
      "云南省分行": "张峰",
      "江苏省分行": "张峰",
      "山西省分行": "张峰",
      "浙江省分行": "张峰",
      "广东省分行": "宋舒",
      "四川省分行": "宋舒",
      "山东省分行": "宋舒",
      "青岛市分行": "宋舒"
    }
